### ISSUE TITLE
Setting the WebDAV server to wrong address crashes the app

### ISSUE THREAD

**Issue by openmac** [PHELAT/Tedu#11]
**Describe the bug**
If you go to settings, click on Backup and choose WebDAV, by entering incorrect server info the app will crash.

**To Reproduce**
1. Go to Settings.
2. Tap on Backup and the WebDAV.
3. Enter wrong info like test.com and random username and password.

It will crash after pressing Save.
It keeps crashing on subsequent launches of the app unless you clear the app's data.

**Expected behavior**
If the server info is incorrect, it should just show me an error.

**Screenshots**
![Screenshot_1595190904](https://user-images.githubusercontent.com/1536307/87884848-5e6d2280-ca26-11ea-9623-7121a8211d95.png)

**Device (please complete the following information):**
 - OS: Android 7.1
 - Tedu Version 1.0.0-alpha02

**Additional context**
Got it from the Play Store, maybe it is already fixed in the third alpha?

**Comment by PHELAT** [comment]
This is now fixed in `1.0.0-alpha03`. Thank you for reporting this bug 🙏🏼.
