### ISSUE TITLE
FirebaseApp is not initialized

### ISSUE THREAD

**Issue by romellfudi** [PHELAT/Tedu#32]
Hi @PHELAT,

I've been trying to run your app, however I couldn't. Just because It always throw the following runtime exception:
```sh
 Unable to create application com.phelat.tedu.Tedu: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.phelat.tedu. Make sure to call FirebaseApp.initializeApp(Context) first
```
https://github.com/PHELAT/Tedu/blob/f27bcda2bab16efa954eae439d68664745e46087/common/analytics/src/main/java/com/phelat/tedu/analytics/di/module/CrashlyticsModule.kt#L14

I put the initialize on the top of the Application Tedu.kt. Nonetheless, it is always crashing. Are there anything else I need to set up?

i really appreciate your help.

**Comment by DHosseiny** [comment]
@PHELAT This happens for me too.

**Comment by romellfudi** [comment]
Hi @PHELAT , I apologize for opening this issue, I forgot the json file. @DHosseiny Just add the file into platform/mobile folder.

**Comment by Kaaveh** [comment]
> Hi @PHELAT , I apologize for opening this issue, I forgot the json file. @DHosseiny Just add the file into platform/mobile folder.

I have this problem right now. How can I solve it?
I don't see any JSON file in platform/mobile folder.
